### ISSUE TITLE
could you please add ftx support to your proxy

### ISSUE THREAD

**Issue by stonetown1975** [mikekonan/exchange-proxy#26]
I liked your kucoin proxy. Could you please add ftx support as well. There are a few opensource go wrappers APIs.
Also it would be great to have binance as well.

Thanks a lot

**Comment by mikekonan** [comment]
As I know FTX does not support WebSockets, but probably it can be integrated over HTTP polling.
Personally, I'm not really interested in integrating these exchanges, if the community really wants, consider donations. 
I have some interest in gate.io, but I will start it after will do some technical improvements to the current codebase.
