### ISSUE TITLE
pull access denied for mikekonan/exchange-proxy,

### ISSUE THREAD

**Issue by kennylbj** [mikekonan/exchange-proxy#29]
Got error when run docker-compose pull

 ERROR: pull access denied for mikekonan/exchange-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by mikekonan** [comment]
sure, it's not ready yet. use old ones: https://hub.docker.com/r/mikekonan/freqtrade-proxy/tags

**Comment by kennylbj** [comment]
Thank you. Really appreciate your work.
