### ISSUE TITLE
Concurrency limit?

### ISSUE THREAD

**Issue by xmflsct** [mikekonan/exchange-proxy#31]
Getting
```
2021/12/29 17:24:25 The incoming connection cannot be served, because 262144 concurrent connections are served. Try increasing Server.Concurrency
```

How to increase concurrency? Thanks!

**Comment by mikekonan** [comment]
Hello, how many proxy clients do you have?

**Comment by xmflsct** [comment]
Not so many, it was around 10-11 freqtrade instances running. I have another VM which runs perfectly with 18 freqtrade instances. I suspect it is because of pairs not clients?

**Comment by mikekonan** [comment]
It's because of amounts of requests, so the limit has to be increased.

**Comment by mikekonan** [comment]
Has proxy crashed?

**Comment by xmflsct** [comment]
No, the proxy did not crash, at least not from Docker's point of view.

The situation just appeared on my other VM which hosts that 18 freqtrade instances. Very weird. Don't know how to properly reproduce the situation. Will monitor a bit further.

**Comment by mikekonan** [comment]
fastHttp server has its own connection pool with a 1024*256 connection limit. So I will make it configurable in the next release

**Comment by mikekonan** [comment]
[#v1.2.1](https://github.com/mikekonan/exchange-proxy/releases/tag/v1.2.1) added `-concurrency-limit` parameter

**Comment by xmflsct** [comment]
Thanks! What is a reasonable amount to set? 1024*256 seems already high, but not sure how many to count for each instance?

**Comment by mikekonan** [comment]
Actually, I don't know, so I recommend you increase that twice until the issue would not occurs. Also, it's could be an issue with freqtrade HTTP client that does not close connections in time.

**Comment by mikekonan** [comment]
What is the output of "ulimit -n"?

**Comment by xmflsct** [comment]
> ulimit -n

In which context?

**Comment by mikekonan** [comment]
On your Linux instance

**Comment by xmflsct** [comment]
On the Linux VM, the result is `1024`.
In the docker container that runs freqtrade instance, the result is `1048576`.

**Comment by mikekonan** [comment]
What is the output of `sudo lsof -Pi -p $PROXY_PID`? From your host

**Comment by mikekonan** [comment]
Also, I suggest checking the amount of opened file descriptions on your instance - https://www.cyberciti.biz/tips/linux-procfs-file-descriptors.html

**Comment by xmflsct** [comment]
`sudo lsof -Pi -p $PROXY_PID` shows a long list.

The total count currently is `222`.
