### ISSUE TITLE
proxy stopped

### ISSUE THREAD

**Issue by mkavinkumar1** [mikekonan/exchange-proxy#39]
FATA[137267] read tcp 10.148.0.40:45262->13.33.96.10:443: read: connection reset by peer  caller="/home/runner/work/exchange-proxy/exchange-proxy/proxy/kucoin/ws.go:312 (*ws).serve" stack="/home/runner/work/exchange-proxy/exchange-proxy/proxy/kucoin/ws.go:312 (*ws).serve\n/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581 goexit"

**Comment by mkavinkumar1** [comment]
![image](https://user-images.githubusercontent.com/33546454/155951377-f80b9656-4dcb-4b6b-a450-4bf41e8f648b.png)

**Comment by mikekonan** [comment]
its expected, let docker will restart it
