### ISSUE TITLE
Latest version on hub.docker?

### ISSUE THREAD

**Issue by amargedon** [mikekonan/exchange-proxy#43]
Maybe this is not an issue, and I do hope it's not. However, I was checking the page https://hub.docker.com/r/mikekonan/freqtrade-proxy/tags?page=1 and the last version published seems 1.1.0 and the latest.

The latest release over here is 1.2.6 and this could match the latest on docker, but as I don't see the specific version tag I'm not sure. Could you clarify (or confirm/deny) the latest is actually 1.2.6?

**Comment by mikekonan** [comment]
Hello, the latest version is 1.2.6.

**Comment by amargedon** [comment]
Ok, thanks!
